package com.jdm.entity;
// Generated 19-Dec-2019 23:01:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "crud")
public class Customer implements java.io.Serializable {

	private Integer custId;
	private String custName;
	private String custAddress;
	private String custPhone;
	private String custEmail;
	private String custGender;
	private Set<Order> orders = new HashSet<Order>(0);

	public Customer() {
	}

	public Customer(String custName, String custAddress, String custPhone, String custEmail, String custGender,
			Set<Order> orders) {
		this.custName = custName;
		this.custAddress = custAddress;
		this.custPhone = custPhone;
		this.custEmail = custEmail;
		this.custGender = custGender;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cust_id", unique = true, nullable = false)
	public Integer getCustId() {
		return this.custId;
	}

	public void setCustId(Integer custId) {
		this.custId = custId;
	}

	@Column(name = "cust_name", length = 45)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "cust_address", length = 45)
	public String getCustAddress() {
		return this.custAddress;
	}

	public void setCustAddress(String custAddress) {
		this.custAddress = custAddress;
	}

	@Column(name = "cust_phone", length = 45)
	public String getCustPhone() {
		return this.custPhone;
	}

	public void setCustPhone(String custPhone) {
		this.custPhone = custPhone;
	}

	@Column(name = "cust_email", length = 45)
	public String getCustEmail() {
		return this.custEmail;
	}

	public void setCustEmail(String custEmail) {
		this.custEmail = custEmail;
	}

	@Column(name = "cust_gender", length = 45)
	public String getCustGender() {
		return this.custGender;
	}

	public void setCustGender(String custGender) {
		this.custGender = custGender;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}