package com.jdm.entity;
// Generated 20-Dec-2019 10:22:23 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Employee generated by hbm2java
 */
@Entity
@Table(name = "employee", catalog = "crud")
public class Employee implements java.io.Serializable {

	private int empId;
	private String empName;
	private String empRole;
	private String empEmail;
	private Integer empSalary;
	private Set<Order> orders = new HashSet<Order>(0);

	public Employee() {
	}

	public Employee(int empId) {
		this.empId = empId;
	}

	public Employee(int empId, String empName, String empRole, String empEmail, Integer empSalary, Set<Order> orders) {
		this.empId = empId;
		this.empName = empName;
		this.empRole = empRole;
		this.empEmail = empEmail;
		this.empSalary = empSalary;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "emp_id", unique = true, nullable = false)
	public int getEmpId() {
		return this.empId;
	}

	public void setEmpId(int empId) {
		this.empId = empId;
	}

	@Column(name = "emp_name", length = 45)
	public String getEmpName() {
		return this.empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

	@Column(name = "emp_role", length = 45)
	public String getEmpRole() {
		return this.empRole;
	}

	public void setEmpRole(String empRole) {
		this.empRole = empRole;
	}

	@Column(name = "emp_email", length = 45)
	public String getEmpEmail() {
		return this.empEmail;
	}

	public void setEmpEmail(String empEmail) {
		this.empEmail = empEmail;
	}

	@Column(name = "emp_salary")
	public Integer getEmpSalary() {
		return this.empSalary;
	}

	public void setEmpSalary(Integer empSalary) {
		this.empSalary = empSalary;
	}
	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "employee")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
