package com.jdm.entity;
// Generated 19-Dec-2019 23:01:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Vehicle generated by hbm2java
 */
@Entity
@Table(name = "vehicle", catalog = "crud")
public class Vehicle implements java.io.Serializable {

	private int VId;
	private String VManufacturer;
	private String VModel;
	private Integer VYear;
	private String VCategory;
	private String VTransmission;
	private Integer VMilleage;
	private String VPlate;
	private String VColor;
	private Float VPrice;
	private Set<Order> orders = new HashSet<Order>(0);

	public Vehicle() {
	}

	public Vehicle(int VId) {
		this.VId = VId;
	}

	public Vehicle(int VId, String VManufacturer, String VModel, Integer VYear, String VCategory, String VTransmission,
			Integer VMilleage, String VPlate, String VColor, Float VPrice, Set<Order> orders) {
		this.VId = VId;
		this.VManufacturer = VManufacturer;
		this.VModel = VModel;
		this.VYear = VYear;
		this.VCategory = VCategory;
		this.VTransmission = VTransmission;
		this.VMilleage = VMilleage;
		this.VPlate = VPlate;
		this.VColor = VColor;
		this.VPrice = VPrice;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "v_id", unique = true, nullable = false)
	public int getVId() {
		return this.VId;
	}

	public void setVId(int VId) {
		this.VId = VId;
	}

	@Column(name = "v_manufacturer", length = 45)
	public String getVManufacturer() {
		return this.VManufacturer;
	}

	public void setVManufacturer(String VManufacturer) {
		this.VManufacturer = VManufacturer;
	}

	@Column(name = "v_model", length = 45)
	public String getVModel() {
		return this.VModel;
	}

	public void setVModel(String VModel) {
		this.VModel = VModel;
	}

	@Column(name = "v_year")
	public Integer getVYear() {
		return this.VYear;
	}

	public void setVYear(Integer VYear) {
		this.VYear = VYear;
	}

	@Column(name = "v_category", length = 45)
	public String getVCategory() {
		return this.VCategory;
	}

	public void setVCategory(String VCategory) {
		this.VCategory = VCategory;
	}

	@Column(name = "v_transmission", length = 45)
	public String getVTransmission() {
		return this.VTransmission;
	}

	public void setVTransmission(String VTransmission) {
		this.VTransmission = VTransmission;
	}

	@Column(name = "v_milleage")
	public Integer getVMilleage() {
		return this.VMilleage;
	}

	public void setVMilleage(Integer VMilleage) {
		this.VMilleage = VMilleage;
	}

	@Column(name = "v_plate", length = 45)
	public String getVPlate() {
		return this.VPlate;
	}

	public void setVPlate(String VPlate) {
		this.VPlate = VPlate;
	}

	@Column(name = "v_color", length = 45)
	public String getVColor() {
		return this.VColor;
	}

	public void setVColor(String VColor) {
		this.VColor = VColor;
	}

	@Column(name = "v_price", precision = 12, scale = 0)
	public Float getVPrice() {
		return this.VPrice;
	}

	public void setVPrice(Float VPrice) {
		this.VPrice = VPrice;
	}
	@JsonIgnore
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "order_has_vehicle", catalog = "crud", joinColumns = {
			@JoinColumn(name = "vehicle_v_id", nullable = false, updatable = true) }, inverseJoinColumns = {
					@JoinColumn(name = "order_o_id", nullable = false, updatable = true) })
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}